{{- if .Values.config.mysql.internal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mysql
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  my-config.cnf: {{ .Values.config.mysql.customConfig | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mysql-init
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-mysql-init
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS {{ .Values.config.mysql.database }};
