{{- if (and .Values.persistence.backup.enabled) }}
apiVersion: stash.appscode.com/v1beta1
kind: BackupBlueprint
metadata:
  name: {{ template "<%- name %>.fullname" . }}
  labels:
    app: {{ template "<%- name %>.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  backend:
    {{ .Values.persistence.backup.type }}:
      {{- if (or (eq "gcs" .Values.persistence.backup.type) (eq "s3" .Values.persistence.backup.type)) }}
      bucket: {{ .Values.persistence.backup.bucket | quote }}
      {{- end }}
      {{- if (eq "s3" .Values.persistence.backup.type) }}
      endpoint: {{ .Values.persistence.backup.endpoint | quote }}
      {{- end }}
      {{- if (eq "azure" .Values.persistence.backup.type) }}
      container: {{ .Values.persistence.backup.container | quote }}
      {{- end }}
      prefix: '{{ .Values.persistence.backup.prefix }}/${TARGET_NAMESPACE}/deployment'
    storageSecretName: {{ template "<%- name %>.fullname" . }}-backup
  schedule: {{ .Values.persistence.backup.schedule | quote }}
  retentionPolicy:
    name: retention-policy
    keepLast: {{ .Values.persistence.backup.keepLast }}
    prune: true
{{- end }}
