apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:<% for (var i = 0; i < configMaps.length; i++) { configMap = configMaps[i]; %>
  <%- _.snakeCase(configMap.key) %>: {{ .Values.config.<%- _.camelCase(configMap.key) %> | quote }}<% } -%>
<%- include('./configmap/databases'); %>
